### ISSUE TITLE
Remove side effects from JS library

### ISSUE THREAD

**Issue by stinovlas** [CZ-NIC/django-fido#173]
`fido2.js` contains side effects (binding listener to `DOMContentLoaded`), which makes importing and using this module quite tricky. We should separate the actual functions to the separate module and only provide thin wrapper that binds the listener in separate file. This allows easy usage as ready-to-use bundle as well as importing it as a library.

**Comment by tpazderka** [comment]
This is a blocker for `1.0` which should be released sooner than later... (end of September...)

**Comment by pazderka** [comment]
I will look into it, it shouldn't take too much time to finish this.
