### ISSUE TITLE
Allow specifying user_verification via settings

### ISSUE THREAD

**Issue by variable** [CZ-NIC/django-fido#193]
My company wants to enforce it to be 'Required' but I don't want to create custom views to set the `user_verification`, can this be set via settings eg.

`user_verification = SETTINGS.user_verification`

thoughts?

**Comment by tpazderka** [comment]
You can override the `user_verification` when you are defining the url:
```
path('fido2', Fido2View.as_view(user_verification=...)
```

**Comment by variable** [comment]
Ah cool didn't realise that I could pass it in like that

**Comment by variable** [comment]
but @tpazderka that doesn't help if I am using the admin to add the authenticators

**Comment by tpazderka** [comment]
Yes, then there is currently no easy way.

The easiest is to subclass `AuthenticatorAdmin` and redefine its `get_urls` to pass the `user_verification` as a kwarg.

But doing it a setting is acceptable as well.

**Comment by variable** [comment]
Cool I will make a PR
