### ISSUE TITLE
Download and parse FIDO Metadata Service

### ISSUE THREAD

**Issue by tpazderka** [CZ-NIC/django-fido#68]
[Metadata Service](https://fidoalliance.org/metadata/) contains info about the attested security level of devices. We should add the ability to download and parse these and add the relevant information to the registered devices.

If enabled, the authenticator level should be queried for every new device and also on a regular basis to catch changes in certification level.

 MDS should be queried on a regular basis and cached in some way (database?)

--------------------------
Design:
`AuthLevel(Enum)` with members `(N, L0, L1, L2, L3, L3+)`

`AuthenticatorMetadata`
* `aaguid(UUIDField)`
* `level(CharField)`
* `attestation_root_certificate(TextField)`

`Authenticator`:
 * `level` -> method to query the cached MDS results.

New setting: `mds_access_token = StringSetting(default=None)`

New management command `download_authenticator_metadata` to download and parse the MDS data.

**Comment by tpazderka** [comment]
This is a basic design, some things we need to consider:
1) We probably need to store devices with `aaid` and `attestationCertificateKeyIdentifiers` as well
2) We might want to save the time of last change for the authenticator status.

Anything else comes to mind?

**Comment by ziima** [comment]
* In `Authenticator` I'd rather have full `Metadata` object, than just level.
* I'd name command `download_authenticator_metadata` to be more generic.
* I'd name the setting `mds_access_token` to be more specific.

**Comment by tpazderka** [comment]
> * In `Authenticator` I'd rather have full `Metadata` object, than just level.

The metadata contain quite a lot of data :/ They are encoded as JSON, so we can store them in a TextField and parse on demand.
> * I'd name command `download_authenticator_metadata` to be more generic.
> * I'd name the setting `mds_access_token` to be more specific.

OK

**Comment by tpazderka** [comment]
Most of this implemented in #69
