### ISSUE TITLE
Replace ugettext with gettext

### ISSUE THREAD

**Issue by stinovlas** [CZ-NIC/django-fido#92]
`django_fido` throws numerous warnings about usage of `ugettext_lazy`:

```
RemovedInDjango40Warning:
    django.utils.translation.ugettext_lazy() is deprecated in favor of django.utils.translation.gettext_lazy().
```

We should consider replacing `ugettext_lazy` with `gettext_lazy` at earliest convenience.

**Comment by tpazderka** [comment]
Closed via #96
